services:
- docker
script:
# Build locally to run test suite
- docker-compose -f docker-comp-test.yml up --abort-on-container-exit
before_deploy:
- pip install --user awscli
- pip install --user awsebcli
- export PATH=$PATH:$HOME/.local/bin
deploy:
- provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/deploy.sh
  on:
    branch: master
  skip_cleanup: true
- provider: script
  script: sh $TRAVIS_BUILD_DIR/scripts/staging.sh
  on:
    branch: staging
  skip_cleanup: true
env:
  global:
  - secure: <TRAVIS SECURE KEY>
  - secure: <TRAVIS SECURE KEY>