# command to run:
# docker-compose -f docker-comp-dev.yml up

# This will start dependencies container & postgres db container with it's associated data volumes container
# and run 'npm run dev'

version: "3"
services:
  # start development client/server container (no HMR)
  dev:
    image: samanthasalley/got-friends-dependencies
    container_name: "got-friends-dev"
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      - postgres-db
      - postgres-data
    command: ["./scripts/start-dev-app.sh", "postgres-db", "dev"]

  # start database container
  postgres-db:
    environment:
      - POSTGRES_PASSWORD=gotme
      - POSTGRES_USER=gotcha
      - POSTGRES_DB=gotfriends
    image: samanthasalley/got-friends-postgres
    container_name: got-friends-postgres
    volumes:
      - dev-db-volume:/var/lib/postgresql/data
      - ./scripts/postgres-db:/postgres-db

# shared volumes for development
volumes:
  dev-db-volume:
  node_modules: