# command to run:
# docker-compose -f docker-comp-test.yml up

# This will start dependencies container
# and run 'npm run test'

version: "3"
services:

  test:
    image: samanthasalley/got-friends-dependencies
    container_name: got-friends-test
    ports:
      - "3000:3000"
    volumes:
      - ./:/usr/src/app
      - node_modules_test:/usr/src/app/node_modules
    command: "npm run test-coverage"

# shared volumes
volumes:
  node_modules_test:
