# Start with Node v10.15.1
FROM node:10.15.1

# Install webpack dev server
RUN npm install webpack -g

# Working directory for application
WORKDIR /usr/src/app

# npm install into /usr/src/app
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json /usr/src/app/
RUN npm install

# replace this with your application server's default port
EXPOSE 3000